Feature/bars 45
BARS-Platform/platform pull request #39
Opened 2019-11-19 18:22 UTC by Halloneo

Реализована логика пермишенов

2019-11-19 20:21 UTC, Helmoz commented on Platform/Platform.Services/Handlers/PermissionHandler.cs
> +    // ReSharper disable once UnusedMember.Global
ну ты понял да

2019-11-19 20:21 UTC, Helmoz commented on Platform/Platform.Services/Handlers/RoleHandler.cs
> +    // ReSharper disable once UnusedMember.Global
ну ты понял да

2019-11-20 06:35 UTC, d4n0n-myself requested changes

2019-11-20 06:35 UTC, d4n0n-myself commented on Platform/Platform.Fodels/Models/Permission.fs
> +    member this.Id
Дублируешь property, сам мне говорил что не стоит так делать

2019-11-20 06:35 UTC, d4n0n-myself commented on Platform/Platform.Fodels/Models/Role.fs
> +    member this.Id
Опять дублирование

2019-11-20 06:35 UTC, d4n0n-myself commented on Platform/Platform.Fodels/Models/UserRole.fs
> +    member this.Id
дублирование

2019-11-20 06:35 UTC, d4n0n-myself commented on Platform/Platform.Fodels/Models/Role.fs
> +type [<AllowNullLiteral>] Role() =
Наверное конструктор надо ограничить до private

2019-11-20 06:35 UTC, d4n0n-myself commented on Platform/Platform.Fodels/Models/UserRole.fs
> +            and set (value) = this.id <- value
Ты уверен ? Этот объект больше похож на ValueObject (согласно DDD). Можно попробовать добавлять такие данные так :
![image](https://user-images.githubusercontent.com/34159440/69213940-a32e7a00-0b76-11ea-888e-7387b1885376.png)

2019-11-20 06:35 UTC, d4n0n-myself commented on Platform/Platform.Migrations/Migrations/20191117093315_RolesAndPermissionsCollection.cs
> +                    RoleId = table.Column<int>(nullable: true)
Не понял ? Изначально, я думал ты будешь делать связку роль-разрешение

2019-11-20 06:35 UTC, d4n0n-myself commented on Platform/Platform.Migrations/MigrationsDbContext.cs
> +				.ToTable("Permissions");
Вроде бы это не обязательно

2019-11-20 06:35 UTC, d4n0n-myself commented on Platform/Platform.Services/Helpers/FSharpListHelper.cs
> +            var enumerator = enumerable.GetEnumerator();
В C# 8.0 добавили такой using. Используя такой using, Dispose будет вызван при выходе из текущего контекста (из текущих фигурных скобок). Не ошибка, больше как фича.
![image](https://user-images.githubusercontent.com/34159440/69214356-cc9bd580-0b77-11ea-89d1-f4dcf655b419.png)

2019-11-20 06:35 UTC, d4n0n-myself commented on Platform/Platform.Web/appsettings.json
> +    "ConnectionString": "Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=postgres"
Это лишнее скорее всего

2019-11-20 06:35 UTC, d4n0n-myself commented on Platform/Platform.Fatabase/ApplicationDbContext.fs
> +        modelBuilder.Entity<Permission>().ToTable("Permissions")
Лишнее? EFCore сам это маппит

2019-11-21 07:35 UTC, d4n0n-myself approved these changes

2019-11-21 08:15 UTC, Helmoz approved these changes
круто

2019-11-21 08:16 UTC, merged