Feature/bars 51
BARS-Platform/platform pull request #67
Opened 2019-12-11 22:25 UTC by Halloneo

Формы на редактирование и создание объектов

2019-12-11 23:18 UTC, Helmoz requested changes

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/components/form/form-dialog.vue
> +        </component>
чисто по общему стилю лучше `<component />`

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/components/form/form-dialog.vue
> +import { Property } from '@/models/property'
отсортируй импорты по их функциональности

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/components/form/form-dialog.vue
> +    return this.model.properties.filter(x => x.displayIn.form === true)
=== true можно убрать, т.к. displayIn.form это boolean

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/components/form/form-dialog.vue
> +          if (fields) {
После filter, если ни один элемент не удовлетворяет условию, вернется пустой массив. Эта проверка вроде как всегда вернет true. лучше проверить `fields.length > 0`

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/components/form/form-dialog.vue
> +  }
можно тернарный оператор использовать

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/components/form/form-dialog.vue
> +        this.ModelValues = []
лучше выделить метод, чтобы избежать дублирования ниже

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/components/form/form-dialog.vue
> +  isSaveEnabled() {
судя по логике это isSaveButtonDisabled

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/components/form/form-dialog.vue
> +      if (value) {
вроде можно заменить на `if(!value || !value.value){result = true}`

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/components/form/form-dialog.vue
> +            columnValue: value.value.id
лучше будет заранее посчитать columnValue по условию  и вызвать 1 раз push

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/components/form/form-dropdown-field.vue
> +    option-value="id"
лишнее?

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/components/form/form-dropdown-field.vue
> +  options: any[] = []
разве не знаем тип?

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/pages/models/Index.vue
> +      v-model="dialog"
v-model кажется лишний

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/pages/models/Index.vue
> +            this.modelValues.push({
опять же, лучше заранее сформировать объект для push'a и только потом запушить его

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/store/modules/Dropdown.ts
> +        notify.error('Произошла ошибка при загрузке данных')
Измени сообщение, чтобы было понятно, что ошибка произошла при загрузке данных для дропдауна

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/store/modules/Model.ts
> +      notify.error('Произошла ошибка при загрузке данных')
При создании

2019-12-11 23:18 UTC, Helmoz commented on Platform/Platform.Web/ClientApp/src/store/modules/Model.ts
> +      notify.error('Произошла ошибка при загрузке данных')
При редактировании

2019-12-12 07:53 UTC, Vaulz commented on Platform/Platform.Web/ClientApp/src/components/form/form-dropdown-field.vue
> +        rowsPerPage: 100
Отображать в форме только 100 записей конечно пиздато, но отображать лучше все я думаю, если pagination, будет null, с сервера тебе вернутся все записи

2019-12-12 09:42 UTC, d4n0n-myself approved these changes

2019-12-12 09:47 UTC, Vaulz approved these changes

2019-12-12 10:22 UTC, Helmoz approved these changes

2019-12-12 10:23 UTC, merged